### ISSUE TITLE
[ios] do not show CameraView

### ISSUE THREAD

**Issue by anton-antohin-cr** [VNAPNIC/flutter-wowza#2]
Hello. Thanks for your plugin.

Could you help me ? 

I can start the stream or stop. I see this from another device that is watching the stream, from the device I am broadcasting, CameraView does not display only a white screen. 

I tested on a real device.
This is relevant only for ios.

**Comment by smew-tech** [comment]
pls check 
iosLicenseKey: "GOSK-9C47-010C-A9B9-EB78-3FBD",
or Size widget cannot define

**Comment by anton-antohin-cr** [comment]
Thanks for such a quick reply.
I forgot about controller.startPreview (); on android startPreview by default
